version: '2'

services:
  postgres:
    image: 'postgres'
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/onebitchat'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: